server:
  port: 8083

spring:
  application:
    name: peekaboot-example-app
  datasource:
  # is configured automatically by spring-boot's compose support

  jpa:
    open-in-view: false

peekaboot:
  dev-toolbar: true

logging:
  level:
    net.osslabz.peekaboot: TRACE

debug: true